### ISSUE TITLE
Issue when installing in pfsense shell

### ISSUE THREAD

**Issue by yahaxs** [jaredhendrickson13/pfsense-api#170]
**_Hi,

I run this command in pfsense shell:
pkg add https://github.com/jaredhendrickson13/pfsense-api/releases/latest/download/pfSense-2.5-pkg-API.txz && /etc/rc.restart_webgui

and we get this error:_**

Crash report begins.  Anonymous machine information:

amd64
12.2-STABLE
FreeBSD 12.2-STABLE plus-RELENG_21_05_1-n202579-3b8ea9b365a pfSense

Crash report details:

PHP Errors:
[17-Oct-2021 12:56:30 Israel] PHP Fatal error:  Uncaught Error: Call to undefined function has_hw_watchdog() in /usr/local/www/system_advanced_misc.php:215
Stack trace:
#0 {main}
  thrown in /usr/local/www/system_advanced_misc.php on line 215
[17-Oct-2021 12:57:32 Israel] PHP Fatal error:  Uncaught Error: Call to undefined function has_hw_watchdog() in /usr/local/www/system_advanced_misc.php:215
Stack trace:
#0 {main}
  thrown in /usr/local/www/system_advanced_misc.php on line 215
[17-Oct-2021 12:58:14 Israel] PHP Fatal error:  Uncaught Error: Call to undefined function watchdogd_enabled() in /etc/inc/service-utils.inc:275
Stack trace:
#0 /etc/inc/service-utils.inc(431): get_services()
#1 /usr/local/www/head.inc(657): find_service_by_name('unbound')
#2 /usr/local/www/services_unbound.php(282): include_once('/usr/local/www/...')
#3 {main}
  thrown in /etc/inc/service-utils.inc on line 275
[17-Oct-2021 13:28:06 Israel] PHP Fatal error:  Uncaught Error: Call to undefined function watchdogd_enabled() in /etc/inc/service-utils.inc:275
Stack trace:
#0 /etc/inc/service-utils.inc(431): get_services()
#1 /usr/local/www/head.inc(657): find_service_by_name('unbound')
#2 /usr/local/www/services_unbound.php(282): include_once('/usr/local/www/...')
#3 {main}
  thrown in /etc/inc/service-utils.inc on line 275

No FreeBSD crash data found.

**Comment by kevin-soutar** [comment]
Hey @yahaxs  running into the same issue, were you able to fix it, or did you have to reinstall?
