### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by interbiznw** [jaredhendrickson13/pfsense-api#438]
2.7.2-RELEASE (amd64)

Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT amd64 1400094 #1 RELENG_2_7_2-n255948-8d2b56da39c: Wed Dec  6 20:45:47 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/obj/amd64/StdASW5b/var/jenkins/workspace/pfSense-CE-snapshots-2_7_2-main/sources/F

Crash report details:

PHP Errors:
[15-Jan-2024 02:21:28 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:07 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:09 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:10 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:10 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:10 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:11 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:11 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:12 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:12 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:13 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100
[15-Jan-2024 02:22:16 America/Los_Angeles] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:100
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 100

No FreeBSD crash data found.

**Comment by jaredhendrickson13** [comment]
Thanks for providing this. This looks to be caused by either pfSense receiving an unexpected response from the GitHub API when checking for available releases, or the releases cache becoming polluted at /usr/local/share/pfSense-pkg-API/releases.json. Either way, some optimizations can be made to prevent the crash if either of these events occur. I can include those in the next patch.

Thanks!

**Comment by sherif-fanous** [comment]
Just ran into this issue while using the latest release with the following stack trace

```
Crash report begins.  Anonymous machine information:

amd64
14.0-CURRENT
FreeBSD 14.0-CURRENT amd64 1400094 #0 plus-RELENG_23_09-n256163-2763857e770: Wed Nov  1 21:18:24 UTC 2023     root@freebsd:/var/jenkins/workspace/pfSense-Plus-snapshots-23_09-main/obj/amd64/WrS3lKLo/var/jenkins/workspace/pfSense-Plus-snapshots-23_09-main/

Crash report details:

PHP Errors:
[09-Apr-2024 12:12:33 America/Toronto] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:102
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 102
[09-Apr-2024 12:13:03 America/Toronto] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:102
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 102
[09-Apr-2024 12:18:07 America/Toronto] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:102
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 102
[09-Apr-2024 12:19:11 America/Toronto] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /etc/inc/api/models/APISystemAPIVersionRead.inc:102
Stack trace:
#0 /etc/inc/api/models/APISystemAPIVersionRead.inc(55): APISystemAPIVersionRead::get_all_available_versions()
#1 /etc/inc/api/models/APISystemAPIVersionRead.inc(69): APISystemAPIVersionRead::get_latest_api_version()
#2 /usr/local/www/api/index.php(26): APISystemAPIVersionRead::is_update_available()
#3 {main}
  thrown in /etc/inc/api/models/APISystemAPIVersionRead.inc on line 102



No FreeBSD crash data found.
```
